### ISSUE TITLE
Initial to-do list

### ISSUE THREAD

**Issue by snowbrett** [northern-latitudes/northern-latitudes.github.io#1]
- [x] Add the SC Chairs. I'll get you that list early tomorrow.
- [x] Remove the description are under the headings of "News" and "Announcements."
- [x] Limit the total quantity of News so the section isn't so large.
- [x] Compress the "About Us" text and logo just enough to make the map show up better when the page is opened. 
- [x] Add the following text next to "About Us:"
  Alaska and Northwest Canada's landscapes support vast, largely-intact landscapes that intertwine with the lives of thousands of people who live there. This biologically, geographically, and culturally diverse region is facing new stressors such as rapid climate change. Meeting these monumental challenges require new ways of working together. Northern Latitudes supports collaboration among hundreds of organizations: federal and state agencies, non-governmental organizations, and Tribes/First Nations across nearly 40 million square kilometers.
- [x] Add the following text to the "About" page (accessed also from "Lean More" link)
  Northern Latitudes partners came together to strategically and deliberately expand cross-LCC collaboration, and to develop a strong, shared narrative focused on benefits to people. 
  Northern Latitudes is an executive committee for the Alaska and Northwest Canada Landscape Conservation Cooperatives (LCCs). In addition to representatives from USGS’ Alaska Climate Science Center, it also includes steering committee chairs and staff for the following LCCs:  Aleutian and Bering Sea Islands, Arctic, North Pacific, Northwest Boreal, and Western Alaska.

**Comment by jlblcc** [comment]
Everything but the SC chairs completed. I reformatted the footer section to show two addresses per line on large screens. Figured we'd just add the chairs to the footer.

**Comment by jlblcc** [comment]
Also added a link to the news section in the navbar.
